# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0928f6845ba41a7d631fac2e348088601d28dd68267f75d6f73a8cbbf55727383fd851b30ef5edd89dc6d381366cccaf926bcb3f0dbf072cde8144b4502960f

test:
  secret_key_base: c464a04d59abc0ce05ccf3cc64eec3ca128bcc8de983194c21b043867909e70a29f58b136128fed63ab79896455b299d9c57b8d74f534417124c5775e421227b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
